### ISSUE TITLE
unicode problems inside the scraper (?)

### ISSUE THREAD

**Issue by egon0** [polarity/MyFeed#4]
as seen here:

http://robert-agthe.de/post/1433930376968-Fracking-Mehr-Erdbeben

**Comment by polarity** [comment]
i already added an iso-8859-1 iconv in the [myfeed-scrape module](https://github.com/polarity/myfeed-scrape) for german umlauts. but i have to rewrite it. im looking into that :)

**Comment by polarity** [comment]
should be fixed now. myfeed-scrape@0.0.30 is live. just update via `npm update`
